---
- name: Good Ansible Role based play
  hosts: all
  gather_facts: false   # Speeds up the execution
  roles:

    - HAproxy
      when: inventory_hostname in groups['frontends']
      
    - apache
      when: inventory_hostname in groups['apps']

    - tomcat
      when: inventory_hostname in groups['apps']

    - postgresql
      when: inventory_hostname in groups['appdbs']

